
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Hao-Ning Wu  ## put your name
title: 'NYU CS 2021'  ## your title
location: New York, NY


## Social Profiles
github: https://github.com/wuhoward
linkedin: https://www.linkedin.com/in/haoningwu/

# Update all the sections by editing the files inside _includes folder.
